-- Generated by scripts/build-corpus-seed.mjs. Do not edit manually.
begin;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Gematria', 'foundation', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 74
from public.phrase_corpus
where phrase = 'Gematria'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 38
from public.phrase_corpus
where phrase = 'Gematria'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 142
from public.phrase_corpus
where phrase = 'Gematria'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 52
from public.phrase_corpus
where phrase = 'Gematria'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('English', 'foundation', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 74
from public.phrase_corpus
where phrase = 'English'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 38
from public.phrase_corpus
where phrase = 'English'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 115
from public.phrase_corpus
where phrase = 'English'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 34
from public.phrase_corpus
where phrase = 'English'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Ordinal', 'foundation', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 73
from public.phrase_corpus
where phrase = 'Ordinal'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 37
from public.phrase_corpus
where phrase = 'Ordinal'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 116
from public.phrase_corpus
where phrase = 'Ordinal'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 44
from public.phrase_corpus
where phrase = 'Ordinal'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Reduction', 'foundation', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 109
from public.phrase_corpus
where phrase = 'Reduction'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 46
from public.phrase_corpus
where phrase = 'Reduction'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 134
from public.phrase_corpus
where phrase = 'Reduction'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 53
from public.phrase_corpus
where phrase = 'Reduction'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Reverse', 'foundation', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 92
from public.phrase_corpus
where phrase = 'Reverse'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 38
from public.phrase_corpus
where phrase = 'Reverse'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 97
from public.phrase_corpus
where phrase = 'Reverse'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 43
from public.phrase_corpus
where phrase = 'Reverse'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Cipher', 'foundation', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 59
from public.phrase_corpus
where phrase = 'Cipher'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 41
from public.phrase_corpus
where phrase = 'Cipher'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 103
from public.phrase_corpus
where phrase = 'Cipher'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 31
from public.phrase_corpus
where phrase = 'Cipher'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Number', 'foundation', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 73
from public.phrase_corpus
where phrase = 'Number'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 28
from public.phrase_corpus
where phrase = 'Number'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 89
from public.phrase_corpus
where phrase = 'Number'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 35
from public.phrase_corpus
where phrase = 'Number'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Research', 'foundation', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 77
from public.phrase_corpus
where phrase = 'Research'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 41
from public.phrase_corpus
where phrase = 'Research'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 139
from public.phrase_corpus
where phrase = 'Research'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 49
from public.phrase_corpus
where phrase = 'Research'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Knowledge', 'concept', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 96
from public.phrase_corpus
where phrase = 'Knowledge'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 42
from public.phrase_corpus
where phrase = 'Knowledge'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 147
from public.phrase_corpus
where phrase = 'Knowledge'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 39
from public.phrase_corpus
where phrase = 'Knowledge'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Wisdom', 'concept', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 83
from public.phrase_corpus
where phrase = 'Wisdom'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 29
from public.phrase_corpus
where phrase = 'Wisdom'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 79
from public.phrase_corpus
where phrase = 'Wisdom'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 34
from public.phrase_corpus
where phrase = 'Wisdom'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Truth', 'concept', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 87
from public.phrase_corpus
where phrase = 'Truth'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 24
from public.phrase_corpus
where phrase = 'Truth'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 48
from public.phrase_corpus
where phrase = 'Truth'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 30
from public.phrase_corpus
where phrase = 'Truth'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Language', 'concept', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 68
from public.phrase_corpus
where phrase = 'Language'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 32
from public.phrase_corpus
where phrase = 'Language'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 148
from public.phrase_corpus
where phrase = 'Language'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 40
from public.phrase_corpus
where phrase = 'Language'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Alphabet', 'concept', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 65
from public.phrase_corpus
where phrase = 'Alphabet'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 29
from public.phrase_corpus
where phrase = 'Alphabet'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 151
from public.phrase_corpus
where phrase = 'Alphabet'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 43
from public.phrase_corpus
where phrase = 'Alphabet'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Calculation', 'concept', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 111
from public.phrase_corpus
where phrase = 'Calculation'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 39
from public.phrase_corpus
where phrase = 'Calculation'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 186
from public.phrase_corpus
where phrase = 'Calculation'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 69
from public.phrase_corpus
where phrase = 'Calculation'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('History', 'concept', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 114
from public.phrase_corpus
where phrase = 'History'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 42
from public.phrase_corpus
where phrase = 'History'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 75
from public.phrase_corpus
where phrase = 'History'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 39
from public.phrase_corpus
where phrase = 'History'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('January', 'month', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 90
from public.phrase_corpus
where phrase = 'January'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 27
from public.phrase_corpus
where phrase = 'January'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 99
from public.phrase_corpus
where phrase = 'January'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 45
from public.phrase_corpus
where phrase = 'January'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('February', 'month', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 96
from public.phrase_corpus
where phrase = 'February'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 42
from public.phrase_corpus
where phrase = 'February'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 120
from public.phrase_corpus
where phrase = 'February'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 48
from public.phrase_corpus
where phrase = 'February'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('March', 'month', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 43
from public.phrase_corpus
where phrase = 'March'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 25
from public.phrase_corpus
where phrase = 'March'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 92
from public.phrase_corpus
where phrase = 'March'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 29
from public.phrase_corpus
where phrase = 'March'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('April', 'month', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 56
from public.phrase_corpus
where phrase = 'April'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 29
from public.phrase_corpus
where phrase = 'April'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 79
from public.phrase_corpus
where phrase = 'April'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 34
from public.phrase_corpus
where phrase = 'April'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('May', 'month', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 39
from public.phrase_corpus
where phrase = 'May'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 12
from public.phrase_corpus
where phrase = 'May'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 42
from public.phrase_corpus
where phrase = 'May'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 15
from public.phrase_corpus
where phrase = 'May'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('June', 'month', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 50
from public.phrase_corpus
where phrase = 'June'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 14
from public.phrase_corpus
where phrase = 'June'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 58
from public.phrase_corpus
where phrase = 'June'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 22
from public.phrase_corpus
where phrase = 'June'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('July', 'month', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 68
from public.phrase_corpus
where phrase = 'July'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 14
from public.phrase_corpus
where phrase = 'July'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 40
from public.phrase_corpus
where phrase = 'July'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 22
from public.phrase_corpus
where phrase = 'July'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('August', 'month', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 89
from public.phrase_corpus
where phrase = 'August'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 17
from public.phrase_corpus
where phrase = 'August'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 73
from public.phrase_corpus
where phrase = 'August'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 37
from public.phrase_corpus
where phrase = 'August'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('September', 'month', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 103
from public.phrase_corpus
where phrase = 'September'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 40
from public.phrase_corpus
where phrase = 'September'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 140
from public.phrase_corpus
where phrase = 'September'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 50
from public.phrase_corpus
where phrase = 'September'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('October', 'month', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 78
from public.phrase_corpus
where phrase = 'October'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 33
from public.phrase_corpus
where phrase = 'October'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 111
from public.phrase_corpus
where phrase = 'October'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 39
from public.phrase_corpus
where phrase = 'October'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('November', 'month', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 94
from public.phrase_corpus
where phrase = 'November'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 40
from public.phrase_corpus
where phrase = 'November'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 122
from public.phrase_corpus
where phrase = 'November'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 41
from public.phrase_corpus
where phrase = 'November'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('December', 'month', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 55
from public.phrase_corpus
where phrase = 'December'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 37
from public.phrase_corpus
where phrase = 'December'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 161
from public.phrase_corpus
where phrase = 'December'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 44
from public.phrase_corpus
where phrase = 'December'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Sunday', 'weekday', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 84
from public.phrase_corpus
where phrase = 'Sunday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 21
from public.phrase_corpus
where phrase = 'Sunday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 78
from public.phrase_corpus
where phrase = 'Sunday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 33
from public.phrase_corpus
where phrase = 'Sunday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Monday', 'weekday', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 72
from public.phrase_corpus
where phrase = 'Monday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 27
from public.phrase_corpus
where phrase = 'Monday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 90
from public.phrase_corpus
where phrase = 'Monday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 27
from public.phrase_corpus
where phrase = 'Monday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Tuesday', 'weekday', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 95
from public.phrase_corpus
where phrase = 'Tuesday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 23
from public.phrase_corpus
where phrase = 'Tuesday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 94
from public.phrase_corpus
where phrase = 'Tuesday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 40
from public.phrase_corpus
where phrase = 'Tuesday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Wednesday', 'weekday', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 100
from public.phrase_corpus
where phrase = 'Wednesday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 37
from public.phrase_corpus
where phrase = 'Wednesday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 143
from public.phrase_corpus
where phrase = 'Wednesday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 44
from public.phrase_corpus
where phrase = 'Wednesday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Thursday', 'weekday', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 116
from public.phrase_corpus
where phrase = 'Thursday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 35
from public.phrase_corpus
where phrase = 'Thursday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 100
from public.phrase_corpus
where phrase = 'Thursday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 46
from public.phrase_corpus
where phrase = 'Thursday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Friday', 'weekday', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 63
from public.phrase_corpus
where phrase = 'Friday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 36
from public.phrase_corpus
where phrase = 'Friday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 99
from public.phrase_corpus
where phrase = 'Friday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 36
from public.phrase_corpus
where phrase = 'Friday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Saturday', 'weekday', 'calendar', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 109
from public.phrase_corpus
where phrase = 'Saturday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 28
from public.phrase_corpus
where phrase = 'Saturday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 107
from public.phrase_corpus
where phrase = 'Saturday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 53
from public.phrase_corpus
where phrase = 'Saturday'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Sun', 'astronomy', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 54
from public.phrase_corpus
where phrase = 'Sun'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 9
from public.phrase_corpus
where phrase = 'Sun'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 27
from public.phrase_corpus
where phrase = 'Sun'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 18
from public.phrase_corpus
where phrase = 'Sun'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Moon', 'astronomy', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 57
from public.phrase_corpus
where phrase = 'Moon'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 21
from public.phrase_corpus
where phrase = 'Moon'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 51
from public.phrase_corpus
where phrase = 'Moon'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 15
from public.phrase_corpus
where phrase = 'Moon'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Mercury', 'astronomy', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 103
from public.phrase_corpus
where phrase = 'Mercury'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 40
from public.phrase_corpus
where phrase = 'Mercury'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 86
from public.phrase_corpus
where phrase = 'Mercury'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 41
from public.phrase_corpus
where phrase = 'Mercury'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Venus', 'astronomy', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 81
from public.phrase_corpus
where phrase = 'Venus'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 18
from public.phrase_corpus
where phrase = 'Venus'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 54
from public.phrase_corpus
where phrase = 'Venus'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 27
from public.phrase_corpus
where phrase = 'Venus'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Earth', 'astronomy', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 52
from public.phrase_corpus
where phrase = 'Earth'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 25
from public.phrase_corpus
where phrase = 'Earth'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 83
from public.phrase_corpus
where phrase = 'Earth'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 29
from public.phrase_corpus
where phrase = 'Earth'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Mars', 'astronomy', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 51
from public.phrase_corpus
where phrase = 'Mars'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 15
from public.phrase_corpus
where phrase = 'Mars'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 57
from public.phrase_corpus
where phrase = 'Mars'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 30
from public.phrase_corpus
where phrase = 'Mars'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Jupiter', 'astronomy', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 99
from public.phrase_corpus
where phrase = 'Jupiter'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 36
from public.phrase_corpus
where phrase = 'Jupiter'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 90
from public.phrase_corpus
where phrase = 'Jupiter'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 45
from public.phrase_corpus
where phrase = 'Jupiter'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Saturn', 'astronomy', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 93
from public.phrase_corpus
where phrase = 'Saturn'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 21
from public.phrase_corpus
where phrase = 'Saturn'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 69
from public.phrase_corpus
where phrase = 'Saturn'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 42
from public.phrase_corpus
where phrase = 'Saturn'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Uranus', 'astronomy', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 94
from public.phrase_corpus
where phrase = 'Uranus'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 22
from public.phrase_corpus
where phrase = 'Uranus'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 68
from public.phrase_corpus
where phrase = 'Uranus'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 41
from public.phrase_corpus
where phrase = 'Uranus'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Neptune', 'astronomy', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 95
from public.phrase_corpus
where phrase = 'Neptune'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 32
from public.phrase_corpus
where phrase = 'Neptune'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 94
from public.phrase_corpus
where phrase = 'Neptune'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 31
from public.phrase_corpus
where phrase = 'Neptune'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_corpus (phrase, category, source, metadata, is_active)
values ('Pluto', 'astronomy', 'starter', '{"seed":true}'::jsonb, true)
on conflict (phrase) do update set
  category = excluded.category,
  source = excluded.source,
  metadata = excluded.metadata,
  is_active = true;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'english-ordinal', 84
from public.phrase_corpus
where phrase = 'Pluto'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'full-reduction', 21
from public.phrase_corpus
where phrase = 'Pluto'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-ordinal', 51
from public.phrase_corpus
where phrase = 'Pluto'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

insert into public.phrase_cipher_values (phrase_id, cipher_id, value)
select id, 'reverse-reduction', 24
from public.phrase_corpus
where phrase = 'Pluto'
on conflict (phrase_id, cipher_id) do update
set value = excluded.value;

commit;
