create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

create table public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  default_cipher_ids text[] not null default array['english-ordinal', 'full-reduction', 'reverse-ordinal', 'reverse-reduction'],
  display_settings jsonb not null default '{}'::jsonb check (jsonb_typeof(display_settings) = 'object'),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table public.custom_ciphers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  description text,
  definition jsonb not null check (jsonb_typeof(definition) = 'object'),
  is_enabled boolean not null default true,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  unique (user_id, name)
);

create table public.research_tables (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  description text,
  color text,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  unique (id, user_id)
);

create table public.research_entries (
  id uuid primary key default gen_random_uuid(),
  table_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  phrase text not null check (char_length(phrase) between 1 and 500),
  results jsonb not null default '{}'::jsonb,
  notes text,
  source_url text,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  foreign key (table_id, user_id)
    references public.research_tables(id, user_id) on delete cascade
);

create table public.calculation_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  phrase text not null check (char_length(phrase) between 1 and 500),
  results jsonb not null check (jsonb_typeof(results) = 'object'),
  created_at timestamptz not null default timezone('utc'::text, now())
);

create table public.phrase_corpus (
  id bigint generated by default as identity primary key,
  phrase text not null unique check (char_length(phrase) between 1 and 500),
  category text,
  source text,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table public.phrase_cipher_values (
  phrase_id bigint not null references public.phrase_corpus(id) on delete cascade,
  cipher_id text not null,
  value bigint not null,
  primary key (phrase_id, cipher_id)
);

create index phrase_cipher_values_lookup_idx
  on public.phrase_cipher_values(cipher_id, value);
create index research_entries_table_created_idx
  on public.research_entries(table_id, created_at desc);
create index calculation_history_user_created_idx
  on public.calculation_history(user_id, created_at desc);

create table public.usage_counters (
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_date date not null default current_date,
  usage_kind text not null,
  usage_count integer not null default 0 check (usage_count >= 0),
  primary key (user_id, usage_date, usage_kind)
);

create trigger user_preferences_set_updated_at
before update on public.user_preferences
for each row execute procedure public.set_updated_at();
create trigger custom_ciphers_set_updated_at
before update on public.custom_ciphers
for each row execute procedure public.set_updated_at();
create trigger research_tables_set_updated_at
before update on public.research_tables
for each row execute procedure public.set_updated_at();
create trigger research_entries_set_updated_at
before update on public.research_entries
for each row execute procedure public.set_updated_at();
create trigger phrase_corpus_set_updated_at
before update on public.phrase_corpus
for each row execute procedure public.set_updated_at();

alter table public.user_preferences enable row level security;
alter table public.custom_ciphers enable row level security;
alter table public.research_tables enable row level security;
alter table public.research_entries enable row level security;
alter table public.calculation_history enable row level security;
alter table public.phrase_corpus enable row level security;
alter table public.phrase_cipher_values enable row level security;
alter table public.usage_counters enable row level security;

create policy "Users manage their preferences"
on public.user_preferences for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their custom ciphers"
on public.custom_ciphers for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their research tables"
on public.research_tables for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their research entries"
on public.research_entries for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their calculation history"
on public.calculation_history for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users view their usage counters"
on public.usage_counters for select to authenticated
using (auth.uid() = user_id);
create policy "Active corpus phrases are readable"
on public.phrase_corpus for select to anon, authenticated
using (is_active);
create policy "Active corpus values are readable"
on public.phrase_cipher_values for select to anon, authenticated
using (
  exists (
    select 1 from public.phrase_corpus
    where phrase_corpus.id = phrase_cipher_values.phrase_id
      and phrase_corpus.is_active
  )
);

comment on table public.usage_counters is
  'Updated only by trusted server code; clients may read their own counters.';
